# Generated by Django 4.2.24 on 2025-09-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='localissue',
            name='content',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AddField(
            model_name='localissue',
            name='impact_level',
            field=models.CharField(choices=[('high', '높음'), ('medium', '보통'), ('low', '낮음')], default='medium', max_length=10, verbose_name='영향도 수준'),
        ),
        migrations.AddField(
            model_name='localissue',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='감성 분석 완료'),
        ),
        migrations.AddField(
            model_name='localissue',
            name='is_trending',
            field=models.BooleanField(default=False, verbose_name='트렌딩 여부'),
        ),
        migrations.AddField(
            model_name='localissue',
            name='sentiment_impact_score',
            field=models.FloatField(default=0.0, verbose_name='감성 영향도'),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='analysis_model',
            field=models.CharField(default='simple', max_length=50, verbose_name='분석 모델'),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='emotion',
            field=models.CharField(choices=[('joy', '기쁨'), ('anger', '분노'), ('sadness', '슬픔'), ('fear', '두려움'), ('surprise', '놀람'), ('disgust', '혐오'), ('neutral', '중립')], default='neutral', max_length=10, verbose_name='세부 감정'),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='emotion_confidence',
            field=models.FloatField(default=0.0, verbose_name='감정 신뢰도'),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='influence_score',
            field=models.FloatField(default=0.0, verbose_name='영향력 지수'),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='processing_time',
            field=models.FloatField(default=0.0, verbose_name='처리 시간(초)'),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='temperature_impact',
            field=models.FloatField(default=0.0, verbose_name='감성온도 영향도'),
        ),
        migrations.AddField(
            model_name='sentimentanalysis',
            name='topics',
            field=models.JSONField(default=list, verbose_name='주제 분류'),
        ),
        migrations.AddField(
            model_name='sentimentsummary',
            name='avg_view_count',
            field=models.FloatField(default=0.0, verbose_name='평균 조회수'),
        ),
        migrations.AddField(
            model_name='sentimentsummary',
            name='sentiment_temperature',
            field=models.FloatField(default=0.0, verbose_name='감성 온도'),
        ),
        migrations.AddField(
            model_name='sentimentsummary',
            name='top_negative_impact',
            field=models.FloatField(default=0.0, verbose_name='최대 부정 영향'),
        ),
        migrations.AddField(
            model_name='sentimentsummary',
            name='top_positive_impact',
            field=models.FloatField(default=0.0, verbose_name='최대 긍정 영향'),
        ),
        migrations.AddField(
            model_name='sentimentsummary',
            name='total_issues',
            field=models.IntegerField(default=0, verbose_name='전체 이슈 수'),
        ),
        migrations.AddField(
            model_name='sentimentsummary',
            name='trending_issues_count',
            field=models.IntegerField(default=0, verbose_name='트렌딩 이슈 수'),
        ),
        migrations.AddField(
            model_name='sentimentsummary',
            name='trending_topics',
            field=models.JSONField(default=list, verbose_name='트렌딩 주제'),
        ),
        migrations.AlterField(
            model_name='localissue',
            name='source',
            field=models.CharField(choices=[('youtube', '유튜브'), ('naver_search', '네이버 검색'), ('naver_news', '네이버 뉴스'), ('instagram', '인스타그램'), ('community', '커뮤니티')], max_length=20, verbose_name='출처'),
        ),
        migrations.AlterField(
            model_name='localissue',
            name='url',
            field=models.URLField(max_length=500, verbose_name='원본 URL'),
        ),
        migrations.AlterField(
            model_name='sentimentanalysis',
            name='keywords',
            field=models.JSONField(default=list, verbose_name='추출 키워드'),
        ),
        migrations.AddIndex(
            model_name='localissue',
            index=models.Index(fields=['sentiment_impact_score'], name='local_issue_sentime_13cd4a_idx'),
        ),
        migrations.AddIndex(
            model_name='localissue',
            index=models.Index(fields=['impact_level', 'published_at'], name='local_issue_impact__398a57_idx'),
        ),
        migrations.AddIndex(
            model_name='localissue',
            index=models.Index(fields=['is_trending', 'is_processed'], name='local_issue_is_tren_e2163a_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysis',
            index=models.Index(fields=['temperature_impact', 'influence_score'], name='sentiment_a_tempera_b69604_idx'),
        ),
        migrations.AddIndex(
            model_name='sentimentanalysis',
            index=models.Index(fields=['emotion', 'emotion_confidence'], name='sentiment_a_emotion_e403a8_idx'),
        ),
    ]
