# Generated by Django 4.2.24 on 2025-09-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('local_data', '0002_localissue_content_localissue_impact_level_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='localissue',
            name='local_issue_sentime_13cd4a_idx',
        ),
        migrations.RemoveIndex(
            model_name='localissue',
            name='local_issue_impact__398a57_idx',
        ),
        migrations.RemoveIndex(
            model_name='localissue',
            name='local_issue_is_tren_e2163a_idx',
        ),
        migrations.RemoveIndex(
            model_name='sentimentanalysis',
            name='sentiment_a_tempera_b69604_idx',
        ),
        migrations.RemoveIndex(
            model_name='sentimentanalysis',
            name='sentiment_a_emotion_e403a8_idx',
        ),
        migrations.RemoveField(
            model_name='localissue',
            name='content',
        ),
        migrations.RemoveField(
            model_name='localissue',
            name='impact_level',
        ),
        migrations.RemoveField(
            model_name='localissue',
            name='is_processed',
        ),
        migrations.RemoveField(
            model_name='localissue',
            name='is_trending',
        ),
        migrations.RemoveField(
            model_name='localissue',
            name='sentiment_impact_score',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='analysis_model',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='emotion',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='emotion_confidence',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='influence_score',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='temperature_impact',
        ),
        migrations.RemoveField(
            model_name='sentimentanalysis',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='sentimentsummary',
            name='avg_view_count',
        ),
        migrations.RemoveField(
            model_name='sentimentsummary',
            name='sentiment_temperature',
        ),
        migrations.RemoveField(
            model_name='sentimentsummary',
            name='top_negative_impact',
        ),
        migrations.RemoveField(
            model_name='sentimentsummary',
            name='top_positive_impact',
        ),
        migrations.RemoveField(
            model_name='sentimentsummary',
            name='total_issues',
        ),
        migrations.RemoveField(
            model_name='sentimentsummary',
            name='trending_issues_count',
        ),
        migrations.RemoveField(
            model_name='sentimentsummary',
            name='trending_topics',
        ),
        migrations.AlterField(
            model_name='localissue',
            name='url',
            field=models.CharField(max_length=200, verbose_name='원본 URL'),
        ),
    ]
