# Generated by Django 4.2.7 on 2025-09-05 13:44

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gu', models.CharField(max_length=50, verbose_name='구')),
                ('gu_code', models.CharField(blank=True, max_length=10, verbose_name='구 코드')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '지역',
                'verbose_name_plural': '지역들',
                'db_table': 'locations',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.location', verbose_name='거주지')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='SentimentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='날짜')),
                ('positive_count', models.IntegerField(default=0, verbose_name='긍정 개수')),
                ('negative_count', models.IntegerField(default=0, verbose_name='부정 개수')),
                ('neutral_count', models.IntegerField(default=0, verbose_name='중립 개수')),
                ('sentiment_score', models.FloatField(default=0.0, verbose_name='감성 점수')),
                ('top_keywords', models.JSONField(default=dict, verbose_name='주요 키워드')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='지역')),
            ],
            options={
                'verbose_name': '감성 요약',
                'verbose_name_plural': '감성 요약들',
                'db_table': 'sentiment_summary',
                'indexes': [models.Index(fields=['location', 'date'], name='sentiment_s_locatio_df23bb_idx')],
                'unique_together': {('location', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SentimentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(max_length=50, verbose_name='콘텐츠 타입')),
                ('content_id', models.PositiveIntegerField(verbose_name='콘텐츠 ID')),
                ('sentiment', models.CharField(choices=[('positive', '긍정'), ('negative', '부정'), ('neutral', '중립')], max_length=10, verbose_name='감성')),
                ('confidence', models.FloatField(verbose_name='신뢰도')),
                ('keywords', models.JSONField(default=list, verbose_name='키워드')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='분석일시')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='지역')),
            ],
            options={
                'verbose_name': '감성 분석',
                'verbose_name_plural': '감성 분석들',
                'db_table': 'sentiment_analysis',
                'indexes': [models.Index(fields=['location', 'sentiment', 'analyzed_at'], name='sentiment_a_locatio_28024c_idx'), models.Index(fields=['content_type', 'content_id'], name='sentiment_a_content_93f105_idx')],
                'unique_together': {('content_type', 'content_id')},
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_number', models.CharField(max_length=50, unique=True, verbose_name='관리번호')),
                ('business_type', models.CharField(choices=[('general', '일반음식점'), ('bakery', '제과점'), ('cafe', '휴게음식점')], max_length=20, verbose_name='업종')),
                ('license_date', models.DateField(blank=True, null=True, verbose_name='인허가일자')),
                ('business_status_code', models.CharField(blank=True, max_length=10, verbose_name='영업상태코드')),
                ('business_status_name', models.CharField(blank=True, max_length=50, verbose_name='영업상태명')),
                ('business_name', models.CharField(blank=True, max_length=200, verbose_name='사업장명')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('area_size', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='소재지면적')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='우편번호')),
                ('road_address', models.TextField(blank=True, verbose_name='도로명주소')),
                ('lot_address', models.TextField(blank=True, verbose_name='지번주소')),
                ('coordinate_x', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='X좌표')),
                ('coordinate_y', models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Y좌표')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='지역')),
            ],
            options={
                'verbose_name': '음식점 정보',
                'verbose_name_plural': '음식점 정보들',
                'db_table': 'restaurant_info',
                'indexes': [models.Index(fields=['location', 'business_type'], name='restaurant__locatio_9ead12_idx'), models.Index(fields=['business_status_code'], name='restaurant__busines_00dc76_idx'), models.Index(fields=['license_date'], name='restaurant__license_5df159_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.TextField(blank=True, verbose_name='출처 URL')),
                ('category', models.CharField(choices=[('weather', '날씨'), ('district_news', '구/동 공지사항'), ('community', '커뮤니티 이슈'), ('secondhand', '중고거래'), ('restaurants', '맛집'), ('local_news', '지역 뉴스')], max_length=50, verbose_name='카테고리')),
                ('title', models.TextField(blank=True, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('processed', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='지역')),
            ],
            options={
                'verbose_name': '원시 데이터',
                'verbose_name_plural': '원시 데이터들',
                'db_table': 'raw_data',
                'indexes': [models.Index(fields=['location', 'category', 'collected_at'], name='raw_data_locatio_934c68_idx'), models.Index(fields=['processed'], name='raw_data_process_0f249b_idx')],
            },
        ),
        migrations.CreateModel(
            name='LocalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('youtube', '유튜브'), ('naver_search', '네이버 검색'), ('naver_news', '네이버 뉴스')], max_length=20, verbose_name='출처')),
                ('title', models.TextField(verbose_name='제목')),
                ('url', models.URLField(verbose_name='URL')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='게시일시')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='지역')),
            ],
            options={
                'verbose_name': '동네 이슈',
                'verbose_name_plural': '동네 이슈들',
                'db_table': 'local_issues',
                'indexes': [models.Index(fields=['location', 'source', 'collected_at'], name='local_issue_locatio_b43c30_idx'), models.Index(fields=['view_count'], name='local_issue_view_co_e2a5ba_idx')],
            },
        ),
        migrations.CreateModel(
            name='DistrictAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(blank=True, max_length=50, verbose_name='게시판 종류')),
                ('post_number', models.CharField(blank=True, max_length=20, verbose_name='게시물 번호')),
                ('title', models.TextField(verbose_name='제목')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='작성자')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='부서명')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='등록일시')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='지역')),
            ],
            options={
                'verbose_name': '구청 공지사항',
                'verbose_name_plural': '구청 공지사항들',
                'db_table': 'district_announcements',
                'indexes': [models.Index(fields=['location', 'created_at'], name='district_an_locatio_092219_idx'), models.Index(fields=['board_type'], name='district_an_board_t_38462b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Briefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='브리핑 날짜')),
                ('content', models.JSONField(verbose_name='브리핑 내용')),
                ('status', models.CharField(choices=[('generating', '생성 중'), ('generated', '생성 완료'), ('failed', '생성 실패')], default='generated', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='지역')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '브리핑',
                'verbose_name_plural': '브리핑들',
                'db_table': 'briefings',
                'indexes': [models.Index(fields=['user', 'date'], name='briefings_user_id_790191_idx'), models.Index(fields=['location', 'date'], name='briefings_locatio_92ae7c_idx')],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
