# Generated by Django 4.2.24 on 2025-09-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='gu',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_provider',
        ),
        migrations.AddField(
            model_name='user',
            name='categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='notification_time',
            field=models.TimeField(default='07:00:00'),
        ),
        migrations.AddField(
            model_name='user',
            name='weekend_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='dong',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_user_set', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
