# Generated by Django 4.2.24 on 2025-09-05 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_location_alter_user_options_remove_user_categories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('youtube', '유튜브'), ('naver_search', '네이버 검색'), ('naver_news', '네이버 뉴스')], max_length=20, verbose_name='출처')),
                ('title', models.TextField(verbose_name='제목')),
                ('url', models.URLField(verbose_name='URL')),
                ('view_count', models.IntegerField(default=0, verbose_name='조회수')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='게시일시')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='수집일시')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.location', verbose_name='지역')),
            ],
            options={
                'verbose_name': '동네 이슈',
                'verbose_name_plural': '동네 이슈들',
                'db_table': 'local_issues',
                'indexes': [models.Index(fields=['location', 'source', 'collected_at'], name='local_issue_locatio_b43c30_idx'), models.Index(fields=['view_count'], name='local_issue_view_co_e2a5ba_idx')],
            },
        ),
    ]
